spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/{dbname}
    username: {dbusername}
    password: {dbpassword}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: {oauthclientid}
            client-secret: {oauthclientsecret}
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
server:
  servlet:
    context-path: /api

jwt:
  secret: SECRET123SECRET123SECRET123SECRET123SECRET123
  expiration: 6000


logging:
  level:
    org:
      springframework:
        security: debug
    root: debug